IEEE1609dot2-cert-chains {iso(1) identified-organization(3) ieee(111)
standards-association-numbered-series-standards(2) wave-stds(1609)
dot2(2) base (1) cert-chains (4)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS

  Time64,
  Uint16
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111)
    standards-association-numbered-series-standards(2) wave-stds(1609)
    dot2(2) base(1) base-types(2)}

  Certificate,
  ImplicitCertificate,
  ExplicitCertificate
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111)
    standards-association-numbered-series-standards(2) wave-stds(1609)
    dot2(2) base(1) schema(1)}
;

CertificateChainFiles ::= CHOICE {
    globalCertificateChainFile GlobalCertificateChainFile,
    localCertificateChainFile LocalCertificateChainFile,
    ...
}

----
--
-- Global Certificate Chain File:
--
-- Contains the full certificate chains of each valid Root, ICA, or PCA that has been issued a
-- certificate. This file is signed by the Policy Generator.
--
----

GlobalCertificateChainFile ::= SEQUENCE {
    version Uint16(0),
    certStore CertificateStore,
    ...
}

----
--
-- Local Certificate Chain File:
--
-- Contains the full certificate chains of each valid Root, ICA, or PCA that has been issued a
-- certificate. This file is signed by the Policy Generator.
--
----

LocalCertificateChainFile ::= SEQUENCE {
    version CompositeVersion,
    requiredCertStore CertificateStore,
    optionalCertStore CertificateStore OPTIONAL,
    ...
}

CompositeVersion ::= SEQUENCE {
	gccfVersion Uint16(0),
	lccfVersion Uint16(0)
}

--
-- Certificate Store
--

CertificateStore ::= SEQUENCE {
    rootCAs SEQUENCE SIZE(0..MAX) OF ExplicitCertificate,
    icaCertChains SEQUENCE SIZE(0..MAX) OF ExplicitCertificate,
    pcaCertChains SEQUENCE SIZE(0..MAX) OF ExplicitCertificate,
    ...
}

END
