IEEE1609dot2-profiles {iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) base (1) profiles (3)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS 
  IdentifiedRegion,
  PsidSspRange,
  SequenceOfIdentifiedRegion
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) base(1) base-types(2)}
 
  Certificate,
  ImplicitCertificate,
  ExplicitCertificate, 
  PsidGroupPermissions,
  SequenceOfPsidGroupPermissions,
  PsidSsp,
  SequenceOfPsidSsp,
  SequenceOfPsidSspRange
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) base(1) schema(1)}

  CrlPsid
FROM IEEE1609dot2Crl {iso(1) identified-organization(3) ieee(111) 
  standards-association-numbered-series-standards(2) wave-stds(1609)  
  dot2(2) crl(3) protocol(2)}

  ObeEnrollmentCertExpirationPoc,
  ObePseudonymCertExpirationPoc,
  ObeIdentificationCertExpirationPoc,
  RseEnrollmentCertExpirationPoc,
  RseApplicationCertExpirationPoc,
  EcaCertExpirationPoc,
  RaCertExpirationPoc,
  LaCertExpirationPoc,
  PcaCertExpirationPoc,
  IcaCertExpirationPoc,
  MaCertExpirationPoc,
  PGCertExpirationPoc,
  RootCaCertExpirationPoc,
  ElectorCertExpirationPoc,
  SecurityMgmtPsid,
  MisbehaviorReportingPsid
FROM Ieee1609dot2ScmsBaseTypes {iso(1) identified-organization(3) ieee(111)
standards-association-numbered-series-standards(2) wave-stds(1609)  dot2(2)
scms (2) interfaces(1) base-types (2)}
;


ObeEnrollmentCertificateScmsPoc ::= ImplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS{sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS { 
      name("")
    }),
    -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(3),
    validityPeriod (WITH COMPONENTS { ...,
      duration (ObeEnrollmentCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions ABSENT,
    certIssuePermissions ABSENT,
    certRequestPermissions (SequenceOfPsidGroupPermissions (SIZE(2)) (CONSTRAINED BY {
      PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS { 
          explicit (SequenceOfPsidSspRange (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS { 
            psid (32), sspRange ABSENT 
          })))
        }),
        minChainDepth(0),
        chainDepthRange(0)
      }),
      PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS{ 
          explicit (SequenceOfPsidSspRange (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS {
            psid (38), sspRange ABSENT 
          })))
        }),
        minChainDepth(1),
        chainDepthRange(0)
      })
    })),
    canRequestRollover(NULL),
    encryptionKey ABSENT,
    verifyKeyIndicator (WITH COMPONENTS {
      reconstructionValue (WITH COMPONENTS {
        compressed-y-0,
        compressed-y-1
      })
    })
  })
})


ObePseudonymCertificateScmsPoc ::= ImplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS { 
      linkageData (WITH COMPONENTS {
        group-linkage-value PRESENT
      })
    }),
    -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(1), -- we will use this value in POC without prejudice
      -- as to whether it will be used in all BSM certs
    validityPeriod (WITH COMPONENTS { ...,
      duration (ObePseudonymCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(2)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(32), 
        ssp ABSENT
      }), 
      PsidSsp (WITH COMPONENTS {
        psid(MisbehaviorReportingPsid), 
        ssp ABSENT
      })
    })),
    certIssuePermissions ABSENT,
    certRequestPermissions ABSENT,
    canRequestRollover ABSENT,
    encryptionKey ABSENT,
    verifyKeyIndicator (WITH COMPONENTS {
      reconstructionValue (WITH COMPONENTS {
        compressed-y-0,
        compressed-y-1
      })
    })
  })
})


ObeIdentificationCertificateScmsPoc ::= ImplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS { 
      name("") -- OBE's ID to be put here
    }),
   -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(3),
    validityPeriod (WITH COMPONENTS { ...,
      duration (ObeIdentificationCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    --appPermissions TO BE ADDED LATER,
    certIssuePermissions ABSENT,
    certRequestPermissions ABSENT,
    canRequestRollover ABSENT,
    encryptionKey ABSENT,
    verifyKeyIndicator (WITH COMPONENTS {
      reconstructionValue (WITH COMPONENTS {
        compressed-y-0,
        compressed-y-1
      })
    })
  })
})


RseEnrollmentCertificateScmsPoc ::= ImplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS{sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS { 
      name("")
    }),
    -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (RseEnrollmentCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions ABSENT,
    certIssuePermissions ABSENT,
    --certRequestPermissions TO BE ADDED LATER,
    canRequestRollover(NULL),
    encryptionKey ABSENT,
    verifyKeyIndicator (WITH COMPONENTS {
      reconstructionValue (WITH COMPONENTS {
        compressed-y-0,
        compressed-y-1
      })
    })
  })
})


RseApplicationCertificateScmsPoc ::= ImplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS { 
      name("") -- RSE's ID to be put here
    }),
    -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (RseApplicationCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    --appPermissions TO BE ADDED LATER,
    certIssuePermissions ABSENT,
    certRequestPermissions ABSENT,
    canRequestRollover ABSENT,
    encryptionKey ABSENT,
    verifyKeyIndicator (WITH COMPONENTS {
      reconstructionValue (WITH COMPONENTS {
        compressed-y-0,
        compressed-y-1
      })
    })
  })
})


EcaCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("eca.poc.campllc.org") -- !!TBD!!
    }),
    -- cracaId set to HashedId3 of the ICA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (EcaCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating Ecassp)
      })
    })),
    certIssuePermissions (SequenceOfPsidGroupPermissions (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS {..., 
	  appPermissions (WITH COMPONENTS {..., 
		explicit (SequenceOfPsidSspRange (SIZE (2)) (CONSTRAINED BY{
		  PsidSspRange (WITH COMPONENTS {
			psid (32), sspRange ABSENT 
		  }),
		  PsidSspRange (WITH COMPONENTS {
			psid (38), sspRange ABSENT 
		  })
		}))
	  }),
	  minChainDepth(1),
	  chainDepthRange(0),
	  eeType({enrol})
    }))),
    certRequestPermissions ABSENT,
    canRequestRollover (NULL),
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


RaCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS{sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("ra.poc.campllc.org") -- !!TBD!!
    }),
    -- cracaId set to HashedId3 of the ICA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (RaCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating Rassp)
      })
    })),
    certIssuePermissions ABSENT,
    certRequestPermissions (SequenceOfPsidGroupPermissions (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS {..., 
	  appPermissions (WITH COMPONENTS {..., 
		explicit (SequenceOfPsidSspRange (SIZE (2)) (CONSTRAINED BY{
		  PsidSspRange (WITH COMPONENTS {
			psid (32), sspRange ABSENT 
		  }),
		  PsidSspRange (WITH COMPONENTS {
			psid (38), sspRange ABSENT 
		  })
		}))
	  })
	}))),
    canRequestRollover(NULL),
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


LaCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS{sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("la.poc.campllc.org") -- !!TBD!!
    }),
    -- cracaId set to HashedId3 of the ICA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (LaCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating Lassp)
      })
    })),
    certIssuePermissions ABSENT,
    certRequestPermissions ABSENT,
    canRequestRollover (NULL),
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


PcaCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("pca.poc.campllc.org") -- !!TBD!!
    }),
    -- cracaId set to HashedId3 of the ICA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (PcaCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating Pcassp)
      })
    })),
    certIssuePermissions (SequenceOfPsidGroupPermissions (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS {..., 
	  appPermissions (WITH COMPONENTS {..., 
		explicit (SequenceOfPsidSspRange (SIZE (2)) (CONSTRAINED BY{
		  PsidSspRange (WITH COMPONENTS {
			psid (32), sspRange ABSENT 
		  }),
		  PsidSspRange (WITH COMPONENTS {
			psid (38), sspRange ABSENT 
		  })
		}))
	  }),
	  minChainDepth(1),
	  chainDepthRange(0)
    }))),
    certRequestPermissions ABSENT,
    canRequestRollover (NULL),
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


IcaCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("ica.poc.campllc.org") -- !!TBD!!
    }),
    -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (IcaCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating Icassp)
      })
    })),
    certIssuePermissions (SequenceOfPsidGroupPermissions (SIZE(4)) (CONSTRAINED BY {
      PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS { 
          explicit (SequenceOfPsidSspRange (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS { 
            psid (32), sspRange ABSENT 
          })))
        }),
        minChainDepth(2),
        chainDepthRange(0),
	    eeType ({app, enrol})
      }),
      PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS{ 
          explicit (SequenceOfPsidSspRange (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS {
            psid (35), sspRange (WITH COMPONENTS {all}) 
          })))
        }),
        minChainDepth(1),
        chainDepthRange(0),
        eeType ({app, enrol})
      }),
	  PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS{ 
          explicit (SequenceOfPsidSspRange (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS {
            psid (CrlPsid), sspRange (WITH COMPONENTS {all})
          })))
        }),
        minChainDepth(1),
        chainDepthRange(0),
        eeType ({app, enrol})
      }),
	  PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS{ 
          explicit (SequenceOfPsidSspRange (SIZE (1)) (WITH COMPONENT (WITH COMPONENTS {
            psid (38), sspRange ABSENT 
          })))
        }),
        minChainDepth(2),
        chainDepthRange(0),
        eeType ({app, enrol})
      })
    })),
    certRequestPermissions ABSENT,
    canRequestRollover (NULL),
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


MaCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("ma.poc.campllc.org") -- !!TBD!!
    }),
    -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (MaCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating MA)
      })
    })),
    certIssuePermissions ABSENT,
    certRequestPermissions ABSENT,
    canRequestRollover (NULL),
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


PGCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {sha256AndDigest}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("pg.poc.campllc.org") -- !!TBD!!
    }),
    -- cracaId set to HashedId3 of the Root CA cert
    crlSeries(2),
    validityPeriod (WITH COMPONENTS { ...,
      duration (PGCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating Policy Generator)
      })
    })),
    certIssuePermissions ABSENT,
    certRequestPermissions ABSENT,
    canRequestRollover (NULL),
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


RootCaCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {self}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("rootca.poc.campllc.org") -- !!TBD!!
    }),
    cracaId, -- set to 00 00 00
    crlSeries(0),                          
    validityPeriod (WITH COMPONENTS { ...,
      duration (RootCaCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating RootCassp)
      })
    })),
    certIssuePermissions (SequenceOfPsidGroupPermissions (SIZE(4)) (CONSTRAINED BY {
      PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS { 
          all
        }),
        minChainDepth(3),
        chainDepthRange(-1),
        eeType ({app, enrol})
      }),
      PsidGroupPermissions ( WITH COMPONENTS {..., 
	    appPermissions (WITH COMPONENTS{ 
          explicit (SequenceOfPsidSspRange (SIZE (3)) (CONSTRAINED BY {
            PsidSspRange (WITH COMPONENTS {
              psid (35), sspRange ABSENT 
            }),             
            PsidSspRange (WITH COMPONENTS {
              psid (38), sspRange ABSENT 
            }), 
            PsidSspRange (WITH COMPONENTS {
              psid (CrlPsid), sspRange ABSENT 
            })
          }))
        }),
        minChainDepth(1),
        chainDepthRange(-1)
      })
    })),
    certRequestPermissions PRESENT,
    canRequestRollover ABSENT,
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})

ElectorCertificateScmsPoc ::= ExplicitCertificate (WITH COMPONENTS { ...,
  issuer (WITH COMPONENTS {self}),
  toBeSigned (WITH COMPONENTS { ...,
    id (WITH COMPONENTS {
      name ("elector.poc.campllc.org") -- !!TBD!!
    }),
    cracaId, -- set to 00 00 00
    crlSeries(0),                          
    validityPeriod (WITH COMPONENTS { ...,
      duration (ElectorCertExpirationPoc)
    }),
    region (WITH COMPONENTS {
      identifiedRegion (SequenceOfIdentifiedRegion (SIZE(3)) (CONSTRAINED BY {
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(124) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(484) 
        }), 
        IdentifiedRegion (WITH COMPONENTS { 
          countryOnly(840) 
        })
      }))
    }),
    assuranceLevel ABSENT,
    appPermissions (SequenceOfPsidSsp (SIZE(1)) (CONSTRAINED BY {
      PsidSsp (WITH COMPONENTS {
        psid(SecurityMgmtPsid)
        --ssp(OER encoding of ScmsSsp indicating Electorssp)
      })
    })),
    certIssuePermissions ABSENT,
    certRequestPermissions ABSENT,
    canRequestRollover ABSENT,
    encryptionKey PRESENT,
    verifyKeyIndicator (WITH COMPONENTS {
      verificationKey (WITH COMPONENTS {
        ecdsaNistP256 (WITH COMPONENTS {
          compressed-y-0,
          compressed-y-1
        })
      })
    })
  })
})


END
