-------------------------------------------------------------------------------
-- COMPONENT-CERT-MANAGEMENT-ERRORS
--
-- The structure in this file defines the possible error occuring during the 
-- management of component certificates.
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------

Ieee1609Dot2ScmsComponentCertificateManagementError
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) errors(2) component-certificate-management (3)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

--------------------------------
-- ComponentCertificateManagementError 
--
-- Generic structure containing the possible error.
--------------------------------
ComponentCertificateManagementError ::= ENUMERATED {
  baseline(1),
  ...
}


END
