-- 
--  Copyright 2017 Crash Avoidance Metrics Partner, VSC5 Consortium
-- 
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
-- 

Ieee1609Dot2ScmsComponentCertificateManagement
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) interfaces(1) component-certificate-management (3) major-version-2(2)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS
  HashedId32, 
  Uint8
FROM IEEE1609dot2BaseTypes {iso(1) identified-organization(3) ieee(111) 
  standards-association-numbered-series-standards(2) wave-stds(1609)  
  dot2(2) base(1) base-types(2) major-version-2(2)}

  ScopedComponentCertificateManagementError
FROM Ieee1609dot2ScmsError {iso(1) identified-organization(3) ieee(111)
  standards-association-numbered-series-standards(2) wave-stds(1609)  dot2(2)
  scms (2) errors(2) complete (1) major-version-2(2)}

  ExplicitCertificate
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111) 
  standards-association-numbered-series-standards(2) wave-stds(1609)  
  dot2(2) base(1) schema(1) major-version-2(2)}

  Time64
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111)
   standards-association-numbered-series-standards(2) wave-stds(1609)
   dot2(2) base(1) base-types(2) major-version-2(2)}

  SecuredCrl
FROM IEEE1609dot2Crl {iso(1) identified-organization(3) ieee(111) 
   standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
   crl(3) protocol(1) major-version-2(2)}

  SignedElectorEndorsement
FROM IEEE1609dot2ScmsProtocol {iso(1) identified-organization(3) ieee(111)
  standards-association-numbered-series-standards(2) wave-stds(1609)
  dot2(2) scms(2) interfaces(1) protocol(1) major-version-2(2)}

;

ScmsComponentCertificateManagementPDU::= CHOICE {
    tbsElectorEndorsement TbsElectorEndorsement,
    ...
}

----
-- Elector Ballots
--
-- These commands are used to add or remove roots and electors from the SCMS.
-- An "endorsement" is a structure with a command type (add/remove for root
-- or elector) along with the certificate to be added or removed.
-- A signed endorsement is a copy of that whole structure with a signature.
-- A "ballot" is a list of signed endorsements.
-- To be valid, a ballot must contain signatures from a quorum of electors.
----

TbsElectorEndorsement ::= SEQUENCE {
    type             EndorsementType,		-- defines the action to be taken
    certificateHash  HashedId32, 	      -- certificate to be added/removed
    effectiveTime    Time64 OPTIONAL	  -- effective time for this message
}

EndorsementType ::= ENUMERATED {
    addRoot (0),	-- add a root CA
    addElector (1),	-- add an elector
    removeRoot (2),	-- remove a root CA
    removeElector (3),  -- remove an elector
    ...
}

ElectorBallot ::= SEQUENCE {
    -- ballot TbsBallot,
    -- the signatures are generated by the Electors (i.e. endorsement ballots)
    -- each signature shall contain a copy of the same TbsElectorEndorsement 
    certificate  ExplicitCertificate OPTIONAL, -- root CA or elector
    endorsements SEQUENCE SIZE(1..MAX) OF SignedElectorEndorsement,
    ...
}



----
-- Composite CRL
-- 
-- A composit CRL contains a list of 1609.2 CRLs, one per CRL series
-- It may also contain ballots to remove Root CAs and Electors 
----

CompositeCrl ::= SEQUENCE {
    securedCrlSeries SEQUENCE SIZE(0..MAX) OF SecuredCrl,
    revokedRootCAs SEQUENCE SIZE(0..MAX) OF ElectorBallot,
    revokedElectors SEQUENCE SIZE(0..MAX) OF ElectorBallot,
    ...
}

END
