-------------------------------------------------------------------------------
-- ECA-EE 
--
-- The structures in this file define the protocol for messages between the
-- ECA and any EE (OBE or RSE) for the purpose of requesting and receiving
-- a new enrollment certificate.
--
-- The enrollment process is always initiated by the EE, typically with the aid
-- of a DCM which provides a trusted connection between the new EE and the
-- ECA.  The enrollment protocol assumes that the DCM does not take an active
-- roll in the enrollment certificate request/response, it is just a trusted
-- network connection point for the EE.  
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------

Ieee1609Dot2EcaEndEntityInterface
{iso(1) identified-organization(3) ieee(111)
standards-association-numbered-series-standards(2) wave-stds(1609)
dot2(2) scms(2) interfaces(1) eca-ee (5)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS

  CrlSeries,
  EccP256CurvePoint,
  GeographicRegion,
  HashedId3,
  HashedId8,
  Hostname,
  PublicEncryptionKey,
  PublicVerificationKey,
  SubjectAssurance,
  Time32,
  Uint8,
  Uint16

FROM IEEE1609dot2BaseTypes {iso(1) identified-organization(3) ieee(111)
	 standards-association-numbered-series-standards(2) wave-stds(1609)
	 dot2(2) base(1) base-types(2)}

  Certificate,
  CertificateId,
  Ieee1609Dot2Data,
  ImplicitCertificate,
  SequenceOfPsidGroupPermissions,
  SequenceOfPsidSsp,
  ValidityPeriod,
  VerificationKeyIndicator

FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111)
	 standards-association-numbered-series-standards(2) wave-stds(1609)
	 dot2(2) base (1) schema (1)}

  SecurityMgmtPsid

FROM Ieee1609dot2ScmsBaseTypes {iso(1) identified-organization(3) ieee(111)
     standards-association-numbered-series-standards(2) wave-stds(1609)  dot2(2)
     scms (2) interfaces(1) base-types (2)}

;

EcaEndEntityInterfacePDU::= CHOICE {
    obeEcaCertRequest     ObeEcaEnrollmentCertificateRequest,
    ecaObeCertResponse    EcaObeEnrollmentCertificateResponse,
    rseEcaCertRequest     RseEcaEnrollmentCertificateRequest,
    ecaRseCertResponse    EcaRseEnrollmentCertificateResponse,
    ...
}

--------------------------------------------------------------------------------------
--
-- Enrollment Sequence Diagram (OBE/RSE)
--
--              OBE                                                     ECA
--               |                                                       |
--   ================================                                    |
--   | Generate Enrollment Key Pair |                                    |
--   ================================                                    |
--               |                                                       |
--   ===============================                                     |
--   |Include Public Key in Request|                                     |
--   ===============================                                     |
--               |                                                       |
--               |============ObeEnrollmentCertificateRequest===========>|
--               |             (TBS Data + PublicKey)                    |
--               |                                              ====================
--               |                                              |Create Enrollment |
--               |                                              |   Certificate    |
--               |                                              |        +         |
--               |                                              |  Reconstruction  |
--               |                                              |      Values      |
--               |                                              ====================
--               |                                                       |
--               |<==========ObeEnrollmentCertificateResponse============|
--               |    (Enrollment Cert + Pub/Priv Reconstruction Data)   |
--               |                                                       |
--     ======================                                            |
--     |     Reconstruct    |                                            |
--     |     Private Key    |                                            |
--     ======================                                            |
--               |                                                       |
--     =======================                                           |
--     | Enrollment Complete |                                           |
--     =======================                                           |
--               |                                                       |
--               |                                                       |
--
-- Refer to ee-ra.asn for description of enrollment procedure.
--
--------------------------------------------------------------------------------------


-------------------------------------------------------------------------------
-- Requests / Responses
-------------------------------------------------------------------------------

-- If the DCM needs to sign the enrollment request, it would use
-- SignedObeEnrollmentRequest or SignedRseEnrollmentRequest. For encryption
-- purposes, the DCM would use SecureObeEnrollmentRequest or
-- SecureRseEnrollmentRequest.
-- The operations for responses are analagous to those for requests.

ObeEcaEnrollmentCertificateRequest ::= CommonEnrollmentCertificateRequest
EcaObeEnrollmentCertificateResponse ::= CommonEnrollmentCertificateResponse

RseEcaEnrollmentCertificateRequest ::= CommonEnrollmentCertificateRequest
EcaRseEnrollmentCertificateResponse ::= CommonEnrollmentCertificateResponse


--------------------------------
-- CommonEnrollmentCertificateRequest
--
-- Enrollment certificate request sent from an EE to an ECA.
--
-- version            version of this response structure
-- currentTime        time when the request was signed
-- requestedStartTime requested validity start time for the enrollment cert
-- tbsData            structure containing requested certificate properties
-- verifyKey          public verification key needed for implicit cert request
--------------------------------
CommonEnrollmentCertificateRequest ::= SEQUENCE {
    version             Uint8(1),
    currentTime         Time32,
    requestedStartTime  Time32, -- certificate start time
    tbsData             ToBeSignedEnrollmentCertificate,
    verifyKey           PublicVerificationKey,
    ...
}


--------------------------------
-- CommonEnrollmentCertificateResponse
-- 
-- Response sent from ECA to an EE to fulfill a certificate request.  The same
-- structure is used for both RSE and OBE enrollment certs.
--
-- version         version of this response structure
-- requestHash     hash of the original certificate request sent to the ECA
-- ecaCert         copy of the ECA certificate
-- raCert          RA certificate used to validate the RA identity
-- raHostname      hostname of the RA that the EE must use 
-- enrollmentCert  signed implicit enrollment certificate
-- privKeyReconstructionS reconstruction value needed for implicit certs
--------------------------------
CommonEnrollmentCertificateResponse ::= SEQUENCE {
	version         Uint8(1),
    requestHash     HashedId8,  -- hash of the original request
    ecaCert         Certificate,
    raCert          Certificate,
    raHostname      Hostname,
    enrollmentCert  Certificate (WITH COMPONENTS { ...,
        type(implicit),
        issuer(WITH COMPONENTS {sha256AndDigest})
    }),
    privKeyReconstructionS EccP256PrivateKeyReconstruction,
    ...
}


--------------------------------
-- ToBeSignedEnrollmentCertificate
-- 
-- This structure populated by an EE when requesting an enrollment certificate. 
--
-- validityPeriod     requested validity period
-- region             list of valid operating regions for the certificate
-- assuranceLevel     octet string that encodes component security properties
-- canRequestRollover flag, indicates that certificate can rollover when true
-- encryptionKey      encryption key for use by EE that is requesting the cert
-- appPermissions     list of PSID/SSP pairs requested for the enrollment cert
--------------------------------
ToBeSignedEnrollmentCertificate ::= SEQUENCE  {
    id                     CertificateId (
        WITH COMPONENTS {..., name PRESENT } |
        WITH COMPONENTS {..., binaryId PRESENT } |
        WITH COMPONENTS {..., none PRESENT }
    ),
    validityPeriod         ValidityPeriod,
    region                 GeographicRegion OPTIONAL,
    assuranceLevel         SubjectAssurance OPTIONAL,
    appPermissions         SequenceOfPsidSsp OPTIONAL,
    canRequestRollover     NULL OPTIONAL,
    encryptionKey          PublicEncryptionKey OPTIONAL,
    ...
}


--------------------------------
-- EccP256PrivateKeyReconstruction
--
-- Reconstruction value needed for implicit certificates
--------------------------------
EccP256PrivateKeyReconstruction ::= OCTET STRING(SIZE(32))

END
