
Ieee1609Dot2EcaEndEntityError
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) errors(2) eca-ee (5)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

EcaEndEntityError ::= ENUMERATED {
  maInvalidCurrentTime, -- currentTime out of range
  maInvalidRequestedStartTime, -- requestedStartTime out of range
  maInvalidPsid, -- passed PSID is invalid for the enrollment
  maInvalidValidityPeriod, --ValidityPeriod out of range
  maInvalidRegion, --GeographicRegion out of range
  maInvalidAssuranceLevel, --SubjectAssurance out of range
  maInvalidEncryptionKey, --response encryption key (PublicEncryptionKey) is invalid
  maInvalidVerifyKey, -- enrollment key (SignedPublicKey) is invalid
  maMalformedRequest, -- everything else that can go wrong in the request 
  ecaInternalServerError, -- ECA failed to process Enrollment; not used yet
  ecaResponseTimeout, -- ECA response timeout; not used yet
  ...
}



END
