
Ieee1609Dot2EndEntityMaInterface
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) interfaces(1) ee-ma (7)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS 
  Uint8,
  Uint16
FROM IEEE1609dot2BaseTypes {iso(1) identified-organization(3) ieee(111) 
	 standards-association-numbered-series-standards(2) wave-stds(1609)  
	 dot2(2) base(1) base-types(2)}

  ImplicitCertificate,
  Ieee1609Dot2Data
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111)
	 standards-association-numbered-series-standards(2) wave-stds(1609)
	 dot2(2) base (1) schema (1)}

;

  EndEntityMaInterfacePDU::= CHOICE {
    misbehaviorReport   MisbehaviorReport,
    ...
  }

  MisbehaviorReport ::= SEQUENCE {
    version 			Uint8(1),
    policyFilename		PolicyFilename,
    reportType 			ReportType,
    evidentiaryData		SEQUENCE (SIZE(1..3)) OF Evidence,
    ...
  }

  PolicyFilename ::= UTF8String (SIZE(0..26))

  ReportType ::= CHOICE {
    proximityPlausibility 	ProximityPlausibility, 
    warningReport 			WarningReport,
    ...
  }

  Evidence ::= SEQUENCE {
    observedNeighborList 	SEQUENCE (SIZE(0..MAX)) OF SignedBSMsWithCertificate,
    reporterWSMs 			SEQUENCE (SIZE(1..10)) OF SignedBSM,
    suspectVehicleList 		SEQUENCE (SIZE(1..10)) OF SignedBSMsWithCertificate,
    ...
  }

  ProximityPlausibility ::= CHOICE {
    default 		NULL,
    ...
  }

  WarningReport ::= CHOICE {
    default 		NULL,
    ...
  }

  SignedBSMsWithCertificate ::= SEQUENCE {
    signedBSMList 			SEQUENCE (SIZE(1..MAX)) OF SignedBSM,
    signingCertificate 		ImplicitCertificate,
    ... 	
  }

  -- unsecuredData is UPER encoded BSM
  SignedBSM ::= Ieee1609Dot2Data (WITH COMPONENTS { ...,
    content (WITH COMPONENTS { 
      signedData (WITH COMPONENTS { ...,
        tbsData (WITH COMPONENTS { ...,
          payload (WITH COMPONENTS {
            data (WITH COMPONENTS { 
              content (WITH COMPONENTS { 
                unsecuredData
              })
            })
          })
        })
      })
    })
  })

  SuspectVehicleList ::= SEQUENCE (SIZE(1..10)) OF SignedBSMsWithCertificate

END
