-------------------------------------------------------------------------------
-- EE-MA 
--
-- The structures in this file define the protocol for messages between an
-- EE (OBE or RSE) and the MA for the purpose of reporting a misbehaving 
-- device.
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------


Ieee1609Dot2EndEntityMaInterface
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) interfaces(1) ee-ma (7)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS 
  Opaque,
  Signature,
  Time32,
  ThreeDLocation,
  Uint8
FROM IEEE1609dot2BaseTypes
{ iso(1) identified-organization(3) ieee(111)
  standards-association-numbered-series-standards(2) wave-stds(1609)  
  dot2(2) base(1) base-types(2) }
;

EndEntityMaInterfacePDU::= CHOICE {
    misbehaviorReport   MisbehaviorReportContents,
    ...
}

--------------------------------
-- MisbehaviorReportContents
--
-- version                version of this response structure
-- misbehavingDeviceInfo  information about the misbehaving device 
-- misbehavingDeviceBSMs  copy of BSMs from misbehaving device
-- reporterDeviceBSMs     copy of BSMs from reporting device
-- sensorInfo             additional sensor information
--------------------------------
MisbehaviorReportContents ::= SEQUENCE {
    version Uint8(1),
    misbehavingDeviceInfo Opaque,  -- placeholder
    misbehavingDeviceBSMs OCTET STRING OPTIONAL,
        -- non-OER encoded ASN.1 messages
    reporterDeviceBSMs OCTET STRING OPTIONAL,
        -- non-OER encoded ASN.1 messages
    sensorInfo Opaque OPTIONAL,
        -- placeholder: non-V2V related sensor information, if available
    ...
}

END
