
Ieee1609Dot2EndEntityMaInterface
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) interfaces(1) ee-ma (7)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS 

  Uint8,
  Uint16

FROM IEEE1609dot2BaseTypes {iso(1) identified-organization(3) ieee(111) 
		standards-association-numbered-series-standards(2) wave-stds(1609)  
		dot2(2) base(1) base-types(2)}

  ImplicitCertificate

FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111)
	 standards-association-numbered-series-standards(2) wave-stds(1609)
	 dot2(2) base (1) schema (1)}

;

EndEntityMaInterfacePDU::= CHOICE {
    misbehaviorReport   MisbehaviorReport,
    ...
}

MisbehaviorReport ::= SEQUENCE {
    version 				Uint8(1),
    policyVersion		PolicyVersion,
    reportType 			ReportType,
    evidentiaryData		SEQUENCE (SIZE(1..3)) OF Evidence,
    ...
}

-- Upper limit on the size to be set later
PolicyVersion ::= UTF8String (SIZE(0..MAX))

ReportType ::= ENUMERATED {
    proximityPlausibility 	(0), 
    warningReport 			(1),
    ...
}

Evidence ::= SEQUENCE {
    observedNeighborList 	SEQUENCE (SIZE(0..MAX)) OF SignedBSMsWithCertificate,
    reporterBSMs 			SEQUENCE (SIZE(1..10)) OF SignedBSMsWithCertificate,
    suspectVehicleList 		SEQUENCE (SIZE(1..10)) OF SuspectVehicleWSMList,
    ...
}

SignedBSMsWithCertificate ::= SEQUENCE {
    signedBSMs 			SEQUENCE (SIZE(1..MAX)) OF WSMData,
    signingCertificate 	ImplicitCertificate,
    ... 	
}

WSMData ::= OCTET STRING -- non-OER encoded signed BSM and security header

SuspectVehicleWSMList ::= SEQUENCE (SIZE(1..10)) OF SignedBSMsWithCertificate

END
