
Ieee1609Dot2EndEntityRaError
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) errors(2) ee-ra (8)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

EndEntityRaError ::= CHOICE {
  ee-ra-soft-error          EeRaSoftErrorCode,
  ee-ra-hard-error          EeRaHardErrorCode,
  ...
}

EeRaSoftErrorCode ::= ENUMERATED {
	-- Device policies out of date, soft error
	raPolicyOutOfDateSoft,
	...
}

EeRaHardErrorCode ::= ENUMERATED {
        -- EE-to-RA authentication failed
        raAuthenticationFailed,
        -- RA-to-EE authentication failed
        eeAuthenticationFailed,
        -- EE tries to communicate without TLS protection
        raNoTLS, 
        -- EE requests invalid URL 
        raRequestedInvalidURL, 
	-- Device policies out of date, hard error
	raPolicyOutOfDateHard, 
	-- Device enrollment certificate blacklisted, expired, unauthorized
	raInvalidCredentials, 
	-- Device signature invalid
	raInvalidSignature,
	-- Unauthorized request permissions invalid
	raInvalidPermissions,
	-- Malformed provisioning request
	raMalformedRequest,
	-- RA does not service this device
	raDoesNotService,
	-- Invalid device system time
	raInvalidSystemTime,
	-- Too many provisioning requests by device
	raTooManyRequests,
        -- Device sent duplicate request
        raDuplicateRequest,
        -- Requested certificate batch not available
        raNoCertFileAvailable,
        -- RA not able to provide .info file
        raNoInfoFileAvailable,
        -- RA not able to provide PCA Certificate Chain file
        raNoPcaCertificateChainFileAvailable,
        -- RA is not able to provide a current Global Certificate Chain file
        raNoGlobalCertificateChainFileAvailable, 
	...
}

END
