
Ieee1609Dot2EndEntityRaError
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) errors(2) ee-ra (8)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

-- RA Triggered Error Codes

EndEntityRaError ::= CHOICE {
  ee-error                  EndEntityError,
  rse-error                 RseError,
  ee-ra-soft-error          EeRaSoftErrorCode,
  ee-ra-hard-error          EeRaHardErrorCode,
  ...
}

EeRaSoftErrorCode ::= ENUMERATED {
	-- Device policies out of date, soft error
	raPolicyOutOfDateSoft,
	...
}

EeRaHardErrorCode ::= ENUMERATED {
    -- EE-to-RA authentication failed
    raAuthenticationFailed,
    -- EE tries to communicate without TLS protection
    raNoTLS, 
    -- EE requests invalid URL 
    raRequestedInvalidURL, 
    -- Device policies out of date, hard error
    raPolicyOutOfDateHard, 
    -- Device enrollment certificate blacklisted, expired, unauthorized
    raInvalidCredentials, 
    -- Device signature invalid
    raInvalidSignature,
    -- Unauthorized request permissions invalid
    raInvalidPermissions,
    -- Malformed provisioning request
    raMalformedRequest,
    -- RA does not service this device
    raDoesNotService,
    -- Invalid device system time
    raInvalidSystemTime,
    -- Too many provisioning requests by device
    raTooManyRequests,
    -- Device sent duplicate request
    raDuplicateRequest,
    -- Requested certificate batch not available
    raNoCertFileAvailable,
    -- RA not able to provide .info file
    raNoInfoFileAvailable,
    -- RA is not able to provide a current Global Certificate Chain file
    raNoGlobalCertificateChainFileAvailable, 
    ...
}

-- EE Triggered Error Codes for Error Logging

EndEntityError ::= ENUMERATED {
    -- RA-to-EE authentication failed
    eeAuthenticationFailed,
    -- EE failed to download 
    eeGlobalPolicyFileDownloadFailed,
    -- EE failed to verify the downloaded Global Policy File
    eeGlobalPolicyVerificationFailed,
    -- EE failed to parse the Global Policy File
    eeGlobalPolicyFileParsingFailed,
    -- EE failed to connect to the RA
    eeConnectionFailed,
    -- EE failed to download the pseudonym certificate batch file
    eeCertFileDownloadFailed,
    -- EE failed to verify the digital signature of an encrypted certificate
    eeCertFileVerificationFailed,
    -- EE failed to decrypt an encrypted certificate
    eeCertFileDecryptionFailed,
    -- EE failed to verify a certificate
    eeCertVerificationFailed,
    -- EE failed to parse certificate or content is incorrect
    eeCertContentFalse,
    -- EE failed to download the *.info file (Misbehaviour Reporting)
    eeInfoFileDownloadFailed,
    -- EE failed to donwload the Global Certificate Chain File
    eeGlobalCertifcateChainFileDownloadFailed,
    ...
}

-- RSE Triggered Error Codes

RseError ::= ENUMERATED {
    -- RSE retries within 2 seconds
    rseRetries,
    -- RSE makes more than 10 retries in 60 minutes
    rseMaxRetries,
    -- RSE request is not signed or signature is invalid
    rseInvalidSignature,
    -- RSE has invalid credentials
    rseInvalidCredentials,
    -- RSE makes an unauthorized request / invalid permissions
    rseInvalidRequest,
    -- RSE makes a malformed request
    rseMalformedRequest,
    -- RSE makes a request to an RA that doesn't service it
    rseRaMismatch,
    -- RSE has invalid system time
    rseInvalidTime,
    ...
}


END
