-------------------------------------------------------------------------------
-- LA-RA-ERRORS
--
-- The structure in this file defines the possible error occuring during a 
-- message exchange between an LA and the RA.
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------

Ieee1609Dot2LaRaError
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) errors(2) la-ra(11)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

--------------------------------
-- LaRaError
--
-- Generic structure containing the possible errors returned by the LA.
--------------------------------
LaRaError ::= CHOICE {
	la-ra	LaRaErrorCode,
	...
}

LaRaErrorCode ::= ENUMERATED {
  invalidPcaKey,        -- no valid key for encryption to PCA available
  invalidIMin,          -- iMin is invalid
  invalidIMax,          -- iMax is invalid
  invalidContinueChain, -- continue chain is neither 0 nor 1
  invalidLinkagechainId,-- linkagechainId is invalid
  invalidJMax,          -- invalid jMax value (e.g. too large)
  ...
}


END
