-------------------------------------------------------------------------------
-- PCA-RA-ERRORS
--
-- The structure in this file defines the possible error occuring during a 
-- message exchange between the PCA and the RA.
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------

Ieee1609Dot2PcaRaError
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) errors(2) pca-ra (15)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;

--------------------------------
-- PcaRaError
--
-- Generic structure containing the possible errors returned by the PCA.
--------------------------------
PcaRaError ::= CHOICE {
	pca-ra-base-error    PcaRaBaseErrorCode,
	pca-ra-request-error PcaRaRequestErrorCode,
	...
}

PcaRaBaseErrorCode ::= ENUMERATED {
	unknownError,                  -- Unknown error
	...
}

--------------------------------
-- PcaRaRequestErrorCode 
--
-- invalidCertificateRequestType invalid certificate type requested
-- invalidType                   invalid type (neither implicit nor explicit 
--                               certificate type)
-- invalidPsidSsp                invalid PSID or SSP
-- invalidRegion                 invalid Region
-- invalidValidity               invalid start, end, duration or expiration time
-- invalidEncryptionPublicKey    an invalid encryption public key is passed
-- invalidSignaturePublicKey     an invalid signing public key is passed
-- invalidEncryptedPreLinkageValue invalid encrypted pre-linkage value is passed
--                                 (e.g. cannot be decrypted)
-- invalidEncryptedGroupPreLinkageValue invalid encrypted group pre-linkage 
--                                value is passed (e.g. cannot be decrypted)
--------------------------------
PcaRaRequestErrorCode ::= ENUMERATED {
	
	invalidCertificateRequestType, -- invalid certificate type requested
	invalidType,                   -- invalid type (neither implicit nor 
                                       -- explicit certificate type)
	invalidPsidSsp,                -- invalid PSID or SSP
	invalidRegion,                 -- invalid Region
	invalidValidity,               -- invalid start, end, duration or 
                                       -- expiration time
	invalidEncryptionPublicKey,    -- an invalid encryption public key is 
                                       -- passed
	invalidSignaturePublicKey,     -- an invalid signing public key is 
                                       -- passed
	invalidEncryptedPreLinkageValue,      -- invalid encrypted pre-linkage 
                                              -- value is passed (e.g. cannot be
                                              -- decrypted)
	invalidEncryptedGroupPreLinkageValue, -- invalid encrypted group 
                                              -- pre-linkage value is passed 
                                              -- (e.g. cannot be decrypted)
 	...
}


END
