-------------------------------------------------------------------------------
-- RA-PG 
--
-- The structures in this file define the protocol for messages between the RA
-- and the PG (Policy Generator) for the purpose of requesting and receiving
-- a custom policy file. 
--
-- Both of these processes are initiated by the MA.
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------

Ieee1609Dot2RaPgInterface
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
scms(2) interfaces(1) ra-pg(16)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN 

EXPORTS ALL;
 
IMPORTS 
  HashedId8,
  Hostname,
  Opaque, 
  Uint8,
  Uint32
FROM IEEE1609dot2BaseTypes {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
    base(1) base-types(2)}

  Countersignature,
  SignerIdentifier
FROM IEEE1609dot2 {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
    base(1) schema(1)}

  HPCR,
  HPCRAndHostInfo,
  LCIAndHostInfo,
  RaHostnameId,
  MaHostnameId
FROM Ieee1609dot2ScmsBaseTypes {iso(1) identified-organization(3) ieee(111)
    standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
    scms(2) interfaces(1) base-types(2)}

  ScopedMaRaBlacklistError,
  ScopedMaRaLCIError
FROM Ieee1609dot2ScmsError {iso(1) identified-organization(3) ieee(111)
    standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
    scms(2) errors(2) complete(1)}
    
  RaPgError
FROM Ieee1609Dot2RaPgError {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ra-pg(16)}

  BasePolicyFile,
  ToBeSignedPolicyData
FROM Ieee1609dot2ScmsPolicyTypes {iso(1) identified-organization(3) ieee(111)
    standards-association-numbered-series-standards(2) wave-stds(1609)  dot2(2)
    scms (2) interfaces(1) policy-types (500)}
;


--------------------------------
-- RaPgInterfacePDU
--
-- All message types for the RA-PG interface PDU
--------------------------------
RaPgInterfacePDU ::= CHOICE {
    raPgPolicySignatureRequest   RaPgPolicySignatureRequestMsg,
    raPgPolicySignatureRequestReply  RaPgPolicySignatureRequestReplyMsg,
    ...
}


--------------------------------
-- ToBeSignedCustomPolicyFile 
--
-- Structure containing the custom policy file modified and then sent by the RA
-- in order to have it signed by the PG
--------------------------------
ToBeSignedCustomPolicyFile ::= ToBeSignedPolicyData( WITH COMPONENTS {...,
    policy(WITH COMPONENTS {...,
        custom PRESENT
    })
})


--------------------------------
-- SignedCustomPolicyFile 
--
-- Structure containing the custom policy file modified by the RA signed by the
-- PG in response to the request by the MA
--------------------------------
SignedCustomPolicyFile ::= BasePolicyFile (WITH COMPONENTS {...,
    tbsData( WITH COMPONENTS {...,
        policy(WITH COMPONENTS {...,
            custom PRESENT
        })
    })
})


--------------------------------
-- RaPgPolicySignatureRequestMsg  
--
-- Request sent from the RA to the PG to sign the modified global parameters 
-- inside a local policy file (LPF). The RA may generate an LPF with a mix of 
-- global parameters and local parameters. The global portion must be approved
-- and signed by the PG before it can be distributed to EEs.  
-- 
-- version            version of this request structure
-- tbs                structure containing the custom policy file to be signed
--------------------------------
RaPgPolicySignatureRequestMsg ::= SEQUENCE {
    version    Uint8(1),
    tbs        ToBeSignedCustomPolicyFile,
    ...
}


--------------------------------
-- RaPgPolicySignatureRequestReplyMsg 
--
-- The response to the policy signature request sent by the PG to the RA
--
-- version            version of this response structure
-- signedFile         structure containing (in case of)
--                    a) success: the signed policy file
--                    b) failure: the corresponding error
--------------------------------
RaPgPolicySignatureRequestReplyMsg ::= SEQUENCE {
    version    Uint8(1),
    signedFile   CHOICE {
       success       SignedCustomPolicyFile,
       failure       RaPgError
    }
}


END

