-------------------------------------------------------------------------------
-- RA-PG-ERRORS
--
-- The structure in this file defines the possible error returned by the PG
-- following a request by the MA for signing a custom policy.
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------

Ieee1609Dot2RaPgError
{iso(1) identified-organization(3) ieee(111) 
standards-association-numbered-series-standards(2) wave-stds(1609)  
dot2(2) scms(2) errors(2) ra-pg(16)}

DEFINITIONS AUTOMATIC TAGS ::= BEGIN

EXPORTS ALL;


--------------------------------
-- RaPgError 
--
-- Possible errors returned by the PG.
--------------------------------
RaPgError ::= ENUMERATED {
  raPgMalformedRequest,  -- the request to the PG was malformed
  raPgSignatureFailed,   -- signing the custom policy failed
  raPgPolicyError,       -- an error in the custom policy occured
  ...
}

END
