-------------------------------------------------------------------------------
-- SCMS-ERRORS
--
-- The structure in this file defines the possible error occuring during the 
-- management of component certificates.
--
-- This file is part of the SCMS protocol developed by CAMP VSC5
-- It depends on the IEEE 1609.2 protocol specification
-------------------------------------------------------------------------------

Ieee1609dot2ScmsError {iso(1) identified-organization(3) ieee(111)
standards-association-numbered-series-standards(2) wave-stds(1609)  dot2(2)
scms (2) errors(2) complete (1)}


DEFINITIONS AUTOMATIC TAGS ::= BEGIN 

EXPORTS ALL;

IMPORTS 

  ScmsCommonError
FROM Ieee1609dot2ScmsCommonError {iso(1) identified-organization(3) ieee(111)
standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
scms (2) errors(2) common(2)}

  ComponentCertificateManagementError
FROM Ieee1609Dot2ScmsComponentCertificateManagementErrorScmsComponentCertificateManagementError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) component-certificate-management(3)}

  EcaEndEntityError
FROM Ieee1609Dot2EcaEndEntityErrorEcaEndEntityError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) eca-ee(5)}

  LaMaError
FROM Ieee1609Dot2LaMaErrorLaMaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) la-ma(9)}

  LaPcaError
FROM Ieee1609Dot2LaPcaErrorLaPcaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) la-pca(10)}

  LaRaError
FROM Ieee1609Dot2LaRaErrorLaRaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) la-ra(11)}

  MaPcaError
FROM Ieee1609Dot2MaPcaErrorMaPcaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ma-pca(13)}

  MaRaError
FROM Ieee1609Dot2MaRaErrorMaRaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ma-ra(14)}

  PcaRaError
FROM Ieee1609Dot2PcaRaErrorPcaRaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) pca-ra(15)}

;

--------------------------------
-- ScmsError 
--
-- Possible errors in the SCMS 
--------------------------------
ScmsError ::= CHOICE {
  common  ScmsCommonError,
  ccm     ComponentCertificateManagementError,
  eca-ee  EcaEndEntityError,
  la-ma   LaMaError,
  la-pca  LaPcaError,
  la-ra   LaRaError,
  ma-pca  MaPcaError,
  ma-ra   MaRaError,
  pca-ra  PcaRaError,
  ...
}


--------------------------------
-- ScopedComponentCertificateManagementError 
--
-- Management of certificates of SCMS component errors
--------------------------------
ScopedComponentCertificateManagementError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ccm})

--------------------------------
-- ScopedEcaEndEntityError 
--
-- ECA-EE errors
--------------------------------
ScopedEcaEndEntityError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {eca-ee})

--------------------------------
-- ScopedLaMaError 
-- 
-- This type is not used (see following la-ma errors)
--------------------------------
ScopedLaMaError ::=
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {la-ma})

--------------------------------
-- ScopedLaMaLIError 
-- 
-- Linkage information request errors
--------------------------------
ScopedLaMaLIError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {la-ma 
                (WITH COMPONENTS {la-ma-base-error} |
                 WITH COMPONENTS {la-ma-linkage-info-error})}
            )

--------------------------------
-- ScopedLaMaLSError 
--
-- Linkage seed request errors
--------------------------------
ScopedLaMaLSError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {la-ma 
                (WITH COMPONENTS {la-ma-base-error} |
                 WITH COMPONENTS {la-ma-linkage-seed-error})}
            )

--------------------------------
-- ScopedLaPcaError
--
-- LA-PCA errors 
--------------------------------
ScopedLaPcaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {la-pca})

--------------------------------
-- ScopedLaRaError
--
-- LA-RA errors 
--------------------------------
ScopedLaRaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {la-ra})

--------------------------------
-- ScopedMaPcaError
--
-- MA-PCA errors
--------------------------------
ScopedMaPcaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ma-pca})

--------------------------------
-- ScopedMaRaError
--
-- MA-RA errors 
--------------------------------
ScopedMaRaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ma-ra})

--------------------------------
-- ScopedMaRaBlacklistError 
--
-- Blacklist request errors
--------------------------------
ScopedMaRaBlacklistError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {ma-ra
                (WITH COMPONENTS {ma-ra-base-error} |
                 WITH COMPONENTS {ma-ra-blacklist-error})}
            )

--------------------------------
-- ScopedMaRaLCIError 
--
-- Linkage chain identifier request errors
--------------------------------
ScopedMaRaLCIError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {ma-ra
                (WITH COMPONENTS {ma-ra-base-error} |
                 WITH COMPONENTS {ma-ra-lci-error})}
            )


--------------------------------
-- ScopedPcaRaError 
--
-- PCA-RA errors
--------------------------------
ScopedPcaRaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {pca-ra})


END
