--<OSS.LONG>--

Ieee1609dot2ScmsError {iso(1) identified-organization(3) ieee(111)
standards-association-numbered-series-standards(2) wave-stds(1609)  dot2(2)
scms (2) errors(2) complete (1)}


DEFINITIONS AUTOMATIC TAGS ::= BEGIN 

EXPORTS ALL;

IMPORTS 

  ScmsCommonError
FROM Ieee1609dot2ScmsCommonError {iso(1) identified-organization(3) ieee(111)
standards-association-numbered-series-standards(2) wave-stds(1609) dot2(2)
scms (2) errors(2) common(2)}

  ComponentCertificateManagementError
FROM Ieee1609Dot2ScmsComponentCertificateManagementErrorScmsComponentCertificateManagementError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) component-certificate-management(3)}

  DcmEcaError
FROM Ieee1609Dot2DcmEcaErrorDcmEcaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) dcm-eca(4)}

  EcaEndEntityError
FROM Ieee1609Dot2EcaEndEntityErrorEcaEndEntityError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) eca-ee(5)}

  EndEntityLopError
FROM Ieee1609Dot2EndEntityLopErrorEndEntityLopError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ee-lop(6)}

  EndEntityMaError
FROM Ieee1609Dot2EndEntityMaErrorEndEntityMaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ee-ma(7)}

  EndEntityRaError
FROM Ieee1609Dot2EndEntityRaErrorEndEntityRaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ee-ra(8)}

  LaMaError
FROM Ieee1609Dot2LaMaErrorLaMaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) la-ma(9)}

  LaPcaError
FROM Ieee1609Dot2LaPcaErrorLaPcaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) la-pca(10)}

  LaRaError
FROM Ieee1609Dot2LaRaErrorLaRaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) la-ra(11)}

  LopMaError
FROM Ieee1609Dot2LopMaErrorLopMaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) lop-ma(12)}

  MaPcaError
FROM Ieee1609Dot2MaPcaErrorMaPcaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ma-pca(13)}

  MaRaError
FROM Ieee1609Dot2MaRaErrorMaRaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) ma-ra(14)}

  PcaRaError
FROM Ieee1609Dot2PcaRaErrorPcaRaError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) pca-ra(15)}

  DcmEndEntityError
FROM Ieee1609Dot2DcmEndEntityErrorDcmEndEntityError
    {iso(1) identified-organization(3) ieee(111) 
    standards-association-numbered-series-standards(2) wave-stds(1609)  
    dot2(2) scms(2) errors(2) dcm-ee(127)}

;

ScmsError ::= CHOICE {
  common  ScmsCommonError,
  ccm     ComponentCertificateManagementError,
  dcm-eca DcmEcaError,
  dca-ee  DcmEndEntityError,
  eca-ee  EcaEndEntityError,
  ee-lop  EndEntityLopError,
  ee-ma   EndEntityMaError,
  ee-ra   EndEntityRaError,
  la-ma   LaMaError,
  la-pca  LaPcaError,
  la-ra   LaRaError,
  lop-ma  LopMaError,
  ma-pca  MaPcaError,
  ma-ra   MaRaError,
  pca-ra  PcaRaError,
  ...
}


ScopedComponentCertificateManagementError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ccm})

ScopedDcmEcaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {dcm-eca})

ScopedDcmEndEntityError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {dca-ee})

ScopedEcaEndEntityError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {eca-ee})

ScopedEndEntityLopError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ee-lop})

ScopedEndEntityMaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ee-ma})

ScopedEndEntityRaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ee-ra})
-- Soft errors
ScopedEndEntityRaSoftError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {ee-ra 
                (WITH COMPONENTS {ee-ra-soft-error})}
            )
-- Hard errors
ScopedEndEntityRaHardError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {ee-ra 
                (WITH COMPONENTS {ee-ra-hard-error})}
            )


-- This type is not used (see following la-ma errors)
ScopedLaMaError ::=
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {la-ma})
-- Linkage information request errors
ScopedLaMaLIError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {la-ma 
                (WITH COMPONENTS {la-ma-base-error} |
                 WITH COMPONENTS {la-ma-linkage-info-error})}
            )
-- Linkage seed request errors
ScopedLaMaLSError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {la-ma 
                (WITH COMPONENTS {la-ma-base-error} |
                 WITH COMPONENTS {la-ma-linkage-seed-error})}
            )

ScopedLaPcaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {la-pca})

ScopedLaRaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {la-ra})

ScopedLopMaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {lop-ma})

ScopedMaPcaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ma-pca})

ScopedMaRaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {ma-ra})
-- Blacklist request errors
ScopedMaRaBlacklistError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {ma-ra
                (WITH COMPONENTS {ma-ra-base-error} |
                 WITH COMPONENTS {ma-ra-blacklist-error})}
            )
-- Linkage chain identifier request errors
ScopedMaRaLCIError ::=
  ScmsError (WITH COMPONENTS {common} | 
             WITH COMPONENTS {ma-ra
                (WITH COMPONENTS {ma-ra-base-error} |
                 WITH COMPONENTS {ma-ra-lci-error})}
            )



ScopedPcaRaError ::= 
  ScmsError (WITH COMPONENTS {common} | WITH COMPONENTS {pca-ra})


END
